"""개념 태그 한→영 사전. 리포트의 '개념별 숙달도'에 노출되므로 영어 뱅크도 영어 태그가 필요하다.
고유 태그가 316개뿐이라 여기서 한 번 번역하면 전 문항에 자동 적용된다(효율).
generate.py가 영어 문제를 만들 때 이 사전으로 concepts를 매핑한다. 누락 시 원문을 그대로 둔다.
"""
CONCEPT_EN = {
    "2배씩 커지기": "doubling", "2의 거듭제곱": "powers of 2", "3분할 전략": "ternary search",
    "60 받아올림": "regrouping by 60", "n번째 항": "nth term", "가르기": "decomposing numbers",
    "가운데 기준": "middle as anchor", "가운데 수 사고": "middle-number reasoning",
    "가장 큰 수 만들기": "making the largest number", "가정하여 풀기": "solve by assuming",
    "가중 평균": "weighted average", "각도": "angles", "간격": "spacing", "간격 문제": "interval problems",
    "간격 사고": "interval reasoning", "같은 것 나누기": "sharing identical items",
    "같은 것이 있는 순열": "permutations with repetition", "개수 세기": "counting",
    "거꾸로 생각하기": "thinking backwards", "거꾸로 풀기": "working backwards", "거듭제곱": "exponents",
    "거속시": "distance-speed-time", "거스름돈": "making change", "거울 사고": "mirror reasoning",
    "겉넓이": "surface area", "격자": "grids", "격자점으로 넓이": "area from lattice points",
    "겹쳐서 세기": "counting through overlaps", "경우 나누어 세기": "counting by cases",
    "경우 따져보기": "casework", "경우의 수": "counting", "계단 문제": "staircase problems",
    "계차 수열": "difference sequences", "계차수열": "difference sequences", "곱": "products",
    "곱 최대": "maximizing a product", "곱셈과 뺄셈": "multiply and subtract",
    "곱의 법칙": "multiplication rule", "곱의 원리": "multiplication principle", "곱해지는 수": "factors",
    "공간 감각": "spatial sense", "공간 대각선": "space diagonal", "공간 도형": "solid figures",
    "공간 좌표": "space coordinates", "공간 지각": "spatial perception", "공간 추론": "spatial reasoning",
    "공배수": "common multiples", "과부족": "excess and deficit", "교란순열": "derangements",
    "규칙": "rules", "규칙 따라가기": "following a rule", "규칙 세우기": "forming a rule",
    "규칙 이해와 적용": "understanding and applying rules", "규칙 적용": "applying rules",
    "규칙 찾기": "finding patterns", "규칙 찾아 일반화": "generalizing a pattern",
    "규칙으로 한꺼번에": "solving all at once with a rule", "규칙의 규칙": "the rule of the rule",
    "기둥의 3분의 1": "one-third of a prism", "기준 고정": "fixing a reference point",
    "기차 문제": "train problems", "꼭짓점 중복": "double-counted vertices", "끝자리 0": "trailing zeros",
    "나머지": "remainders", "나머지 사고": "remainder reasoning", "나머지 주기": "remainder cycles",
    "나머지로 거듭제곱": "exponents via remainders", "나이 문제": "age problems", "남은 양": "leftover amount",
    "넓이": "area", "넓이비": "area ratio", "논리 추론": "logical reasoning", "농도": "concentration",
    "누적": "accumulation", "다각형 내각": "interior angles of polygons", "다리 세기": "counting legs",
    "다면체": "polyhedra", "단위 바꾸기": "unit conversion", "단위 시간 사고": "per-unit-time reasoning",
    "단위량": "unit quantity", "단위량 먼저": "find the unit amount first", "달력 구조": "calendar structure",
    "닮음": "similarity", "대각선": "diagonals", "대각선 교점": "diagonal intersections",
    "대응 규칙": "correspondence rule", "대칭": "symmetry", "대칭축": "axes of symmetry",
    "동전 조합": "coin combinations", "두 번 세고 나누기": "count twice, then divide",
    "둘러싸고 빼기": "surround and subtract", "둘러싸기": "enclosing", "둘레": "perimeter",
    "둘레는 다르다": "perimeter differs", "둘레와 넓이": "perimeter and area", "등비 규칙": "geometric rule",
    "등비수열": "geometric sequences", "등차": "arithmetic", "등차수열": "arithmetic sequences",
    "등차수열 합": "sum of an arithmetic sequence", "따라잡기": "catching up",
    "똑같이 나눠담기": "sharing equally", "마주 보는 세 쌍": "three opposite pairs",
    "마지막 날 함정": "the last-day trap", "만남 문제": "meeting problems", "면 세기": "counting faces",
    "모눈": "grid squares", "모서리 세기": "counting edges", "모서리는 두 면이 공유": "edges shared by two faces",
    "반복 규칙": "repeating patterns", "반복 변화": "repeated change", "반복 주기": "repeating cycles",
    "반복 허용": "repetition allowed", "반비례": "inverse proportion", "배 관계 변화": "changing ratios",
    "배수": "multiples", "배수 남기기": "sieving multiples", "백분율": "percentages",
    "벌레먹은셈": "cryptarithm (missing digits)", "변 공유": "shared sides", "복면산": "cryptarithm",
    "부분과 전체": "part and whole", "분수": "fractions", "불변량": "invariants", "불변의 규칙": "invariant rule",
    "비": "ratios", "비둘기집 원리": "pigeonhole principle", "비례": "proportion", "비례 관계": "proportional relations",
    "비율": "rates", "빠짐없이 경우 세기": "exhaustive counting", "빠짐없이 짝짓기": "pairing without omission",
    "뿔의 부피": "volume of a cone", "사각수": "square numbers", "사다리꼴 넓이": "area of a trapezoid",
    "사라지는 양 세기": "counting what disappears", "삼각수": "triangular numbers", "삼각형 개수": "counting triangles",
    "삼각형 내각": "angles of a triangle", "삼각형 넓이": "area of a triangle", "서로소 개수": "count of coprimes",
    "섞기": "mixing", "선대칭": "line symmetry", "세 몫으로 나누기": "splitting into three parts",
    "세 수": "three numbers", "세기": "counting", "세제곱 합": "sum of cubes", "소수": "prime numbers",
    "소인수 5": "the prime factor 5", "소인수분해": "prime factorization", "속력의 합": "sum of speeds",
    "수 세기": "counting", "수 피라미드": "number pyramid", "수열의 합": "sum of a sequence",
    "수열의 항": "terms of a sequence", "수직선": "number line", "순서 구별하기": "distinguishing order",
    "순서 무관": "order-independent", "순서 무시 세기": "counting without order", "순서 비교": "comparing order",
    "순서 세기": "counting arrangements", "순서 세우기": "putting in order", "순서 있는 뽑기": "ordered selection",
    "순서 있는 짝": "ordered pairs", "순서 정하기": "deciding an order", "순서 추론": "order reasoning",
    "숨은 거리": "the hidden distance", "숨은 관계 발견": "finding a hidden relationship",
    "숨은 길이": "the hidden length", "시간 계산": "time calculation", "시계 눈금": "clock marks",
    "시계 종": "clock chimes", "시소": "seesaw", "시침의 이동": "movement of the hour hand",
    "쌓기나무": "stacking blocks", "앞 두 수의 합": "sum of the two before", "약속 연산": "custom operation",
    "약수": "divisors", "약수 추론": "divisor reasoning", "약수 판별": "identifying divisors",
    "약수의 개수": "number of divisors", "약수의 합": "sum of divisors", "양 끝 포함": "both ends included",
    "여사건": "complementary events", "여집합 중복": "complement pairs", "역산": "reverse calculation",
    "역연산": "inverse operations", "연립 추론": "simultaneous reasoning", "연속 자연수 합": "sum of consecutive numbers",
    "연속 할인": "successive discounts", "연속수": "consecutive numbers", "연속한 수": "consecutive numbers",
    "염주순열": "necklace permutations", "영역 세기": "counting regions", "오일러 공식": "Euler's formula",
    "오일러 정리": "Euler's theorem", "오일러 피 함수": "Euler's totient function",
    "올바른 배열 세기": "counting valid arrangements", "완전수": "perfect numbers", "완전제곱수": "perfect squares",
    "외각": "exterior angles", "요일": "days of the week", "욕심쟁이 방법": "greedy method",
    "원순열": "circular permutations", "위치 사고": "position reasoning", "위치로 나누어 세기": "counting by position",
    "윤년 규칙": "leap-year rule", "이행성": "transitivity", "일률": "work rate", "일의 양": "amount of work",
    "일의 자리": "the units digit", "일정하게 커지는 수": "numbers growing by a constant",
    "일차부정방정식": "linear Diophantine equations", "입체도형": "solid figures", "자료 읽기": "reading data",
    "자료 정리": "organizing data", "자료 해석": "interpreting data", "자르기 횟수": "number of cuts",
    "자리값": "place value", "자리값 거꾸로": "reversing place value", "자리값 사고": "place-value reasoning",
    "자리별로 세기": "counting by place", "자릿값": "place value", "자연수의 분할": "integer partitions",
    "장애물": "obstacles", "저울": "balance scale", "적어도": "at least", "전개도": "nets",
    "전체의 일부": "part of a whole", "점화식": "recurrence relations", "정다각형": "regular polygons",
    "정렬": "sorting", "정사각형": "squares", "정사각형 만들기": "making squares", "제곱수": "square numbers",
    "제곱수 합": "sum of squares", "조건 따지기": "checking conditions", "조건 맞추기": "meeting conditions",
    "조건 좁혀 가기": "narrowing conditions", "조건 함께 만족하기": "satisfying conditions together",
    "조합": "combinations", "조합으로 세기": "counting with combinations", "조화평균": "harmonic mean",
    "주고받기": "giving and taking", "주기": "cycles", "주기와 나머지": "cycles and remainders",
    "중간값": "the middle value", "중국인의 나머지 정리": "Chinese remainder theorem",
    "중복 나누기": "dividing out repeats", "중복 빼기": "subtracting overlaps", "중복 없이 세기": "counting without repeats",
    "중복조합": "combinations with repetition", "중앙값": "median", "지렛대(반비례)": "levers (inverse proportion)",
    "직사각형 세기": "counting rectangles", "진실과 거짓": "truth and lies", "진약수의 합": "sum of proper divisors",
    "집합": "sets", "집합 나누기": "partitioning a set", "짝지어 더하기": "pairing to add",
    "짝지어 세기": "counting in pairs", "차이 사고": "difference reasoning", "차이 줄이기": "closing the gap",
    "차이로 나누기": "dividing by the difference", "차이의 규칙": "the rule of the differences",
    "채우기와 빼기": "fill and subtract", "체계적 세기": "systematic counting", "체계적으로 세기": "systematic counting",
    "총합 사고": "total-sum reasoning", "최단 경로": "shortest paths", "최대공약수": "greatest common divisor",
    "최댓값·최솟값": "maximum and minimum", "최빈값": "mode", "최소 보충": "minimum to add",
    "최소 이동": "fewest moves", "최소 횟수": "fewest times", "최소공배수": "least common multiple",
    "최소공배수 관계": "LCM relationships", "최악의 경우": "the worst case", "측정": "measurement",
    "치환": "substitution", "카탈란 수": "Catalan numbers", "칸 세기": "counting cells",
    "콜라츠": "Collatz", "크기 순 비교": "comparing by size", "타일 깔기": "tiling",
    "탈락으로 세기": "counting by elimination", "테두리 세기": "counting the border", "토너먼트": "tournaments",
    "톱니바퀴": "gears", "평균": "average", "평균 변화": "change in average", "평균 속력": "average speed",
    "평행사변형 넓이": "area of a parallelogram", "포함배제": "inclusion-exclusion", "피보나치": "Fibonacci",
    "피타고라스": "Pythagorean theorem", "픽의 정리": "Pick's theorem", "필승 전략": "winning strategy",
    "한 개 값 구하기": "finding the unit price", "함수 반복": "iterating a function", "합 나누기": "dividing the sum",
    "합과 가운데": "sum and middle", "합과 곱": "sum and product", "합과 차": "sum and difference",
    "합으로 비교": "comparing by totals", "합으로 역산": "back-solving from the total", "합의 규칙": "the rule of the sum",
    "합의 숨은 규칙": "the hidden rule of a sum", "합이 같을 때 곱 최대": "max product for a fixed sum",
    "합이 일정": "constant sum", "합차법": "sum-and-difference method", "홀수의 합": "sum of odd numbers",
    "홀짝 보존": "parity invariance", "확률": "probability", "회전·대칭 겹침": "rotational and reflective symmetry",
}
